---

- name: Download manager config file
  aws_s3:
    bucket: "{{ bucket }}"
    mode: get
    object: orchestration/manager.json
    dest: manager_config.json
- name: Get manager IP
  shell: "cat manager_config.json | jq -r '.manager_ip'"
  register: manager_ip
- name: Get manager token
  shell: "cat manager_config.json | jq -r '.manager_token'"
  register: manager_token
- name: Get worker token
  shell: "cat manager_config.json | jq -r '.worker_token'"
  register: worker_token
- name: Join cluster
  shell: >
    docker swarm leave --force || true &&
    docker swarm join
    --token={{ manager_token.stdout }}
    {{ manager_ip.stdout }}
