---

- name: Enable repo
  shell: amazon-linux-extras install epel -y

- name: install fail2ban
  yum:
    name:
      - fail2ban
    state: latest

- name: Copy config file
  copy: src=etc/fail2ban/jail.local dest=/etc/fail2ban/jail.local

- name: Start service
  shell: systemctl restart fail2ban.service
