#cloud-config

cloud_init_modules:
  - seed_random
  - bootcmd
  - [write-files, always]
  - growpart
  - resizefs
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - users-groups
  - ssh

cloud_config_modules:
  - [timezone, always]
  - [package-update-upgrade-install, always]
  - [runcmd, always]

cloud_final_modules:
  - [scripts-user, always]

write_files:
  - path: /root/.aws/config
    permissions: 0644
    content: |
      [default]
      region=us-east-1
  - path: /etc/environment
    append: true
    content: |
      SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}

timezone: Europe/London

packages:
  - curl
  - jq
  - python-pip
  - git

runcmd:
  - chmod +x /home/ec2-user/ansible/provision.sh
  - sh -c /home/ec2-user/ansible/provision.sh
