#cloud-config

cloud_init_modules:
  - seed_random
  - bootcmd
  - [write-files, always]
  - growpart
  - resizefs
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - users-groups
  - ssh

cloud_config_modules:
  - [timezone, always]
  - [package-update-upgrade-install, always]
  - [runcmd, always]

cloud_final_modules:
  - [scripts-user, always]

write_files:
  - path: /home/ec2-user/.aws/config
    permissions: 0644
    content: |
      [default]
      region=${REGION}
  - path: /etc/environment
    append: true
    content: |
      ENV=${ENV}
      SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      REGION=${REGION}
      BUCKET=${BUCKET}

timezone: Europe/London

packages:
  - curl
  - jq
  - python-pip
  - git

runcmd:
  - chown -R ec2-user:ec2-user /home/ec2-user
  - git clone https://github.com/zeitgeist2018/infrastructure.git
  - mv infrastructure/ansible /home/ec2-user/ansible && rm -r infrastructure
  - chmod +x /home/ec2-user/ansible/provision.sh
  - sudo sh -c /home/ec2-user/ansible/provision.sh
